# Generated by Django 3.1.3 on 2021-08-22 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(db_column='id_video', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video',
                'managed': True,
            },
        ),
    ]
